#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SOURCE_ARTIFACT_REL="${SOURCE_ARTIFACT_REL:-traces/analysis/phase4-conv2d-k3-family-scout-20260316T091108Z}"
OUT_DIR_REL="${OUT_DIR_REL:-templates/phase5_conv2d_k3_h8_band_6496}"
FAMILY_ID="${FAMILY_ID:-phase5_conv2d_k3_h8_band_6496_v1}"
SOURCE_ARTIFACT="$REPO_ROOT/$SOURCE_ARTIFACT_REL"
OUT_DIR="$REPO_ROOT/$OUT_DIR_REL"

ANCHOR_HEIGHT="${ANCHOR_HEIGHT:-8}"
ANCHOR_WIDTH="${ANCHOR_WIDTH:-128}"
LOW_WIDTH="${LOW_WIDTH:-104}"
MID_WIDTH="${MID_WIDTH:-128}"
HIGH_WIDTH="${HIGH_WIDTH:-152}"
TARGET_WIDTHS_CSV="${TARGET_WIDTHS_CSV:-104,116,128,140,152}"
TILE_SIZE="${TILE_SIZE:-8}"
EO_PAYLOAD_LEN="${EO_PAYLOAD_LEN:-6496}"
LOOKUP_CAP="${LOOKUP_CAP:-999999}"
PREDICT_MODE="${PREDICT_MODE:-threepoint}"

pairs=(
  "p32 32"
  "p64 64"
  "p128 128"
)

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "required command not found: $1" >&2
    exit 1
  }
}

need_cmd cargo
need_cmd python3

[[ -d "$SOURCE_ARTIFACT" ]] || {
  echo "source artifact not found: $SOURCE_ARTIFACT" >&2
  exit 1
}

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

copy_case_files() {
  local src_dir="$1"
  local dst_dir="$2"
  mkdir -p "$dst_dir"
  cp "$(find "$src_dir" -maxdepth 1 -name '*.tflite' ! -name '*_edgetpu.tflite' | head -n1)" "$dst_dir/"
  cp "$(find "$src_dir" -maxdepth 1 -name '*_edgetpu.tflite' | head -n1)" "$dst_dir/"
  cp "$(find "$src_dir" -maxdepth 1 -name '*.metadata.json' | head -n1)" "$dst_dir/"
}

lookup_from_predicted() {
  local payload_len="$1"
  local base_exec="$2"
  local target_exec="$3"
  local predicted_patchspec="$4"
  local out_lookup="$5"
  python3 - <<'PY' "$payload_len" "$base_exec" "$target_exec" "$predicted_patchspec" "$out_lookup" "$REPO_ROOT"
import pathlib, sys
sys.path.insert(0, str(pathlib.Path(sys.argv[6]) / "tools"))
import parse_edgetpu_executable as pe

payload_len = int(sys.argv[1])
base_exec = pathlib.Path(sys.argv[2])
target_exec = pathlib.Path(sys.argv[3])
predicted_patchspec = pathlib.Path(sys.argv[4])
out_lookup = pathlib.Path(sys.argv[5])

def read_chunk(path):
    blob = path.read_bytes()
    root = pe._parse_root_table(blob, 0, file_identifier=None)
    tables = pe._read_vector_table_field(root, 5)
    return bytearray(pe._read_vector_bytes_field(tables[0], 0))

base = read_chunk(base_exec)
target = read_chunk(target_exec)
patched = bytearray(base)
for raw in predicted_patchspec.read_text().splitlines():
    clean = raw.split("#", 1)[0].strip()
    if not clean:
        continue
    fields = clean.split()
    if len(fields) != 3:
        continue
    plen, off, val = [int(x, 0) for x in fields]
    if plen != payload_len:
      raise SystemExit(f"unexpected payload len {plen} in {predicted_patchspec}")
    patched[off] = val

lines = ["# lookup residue generated by phase5 freeze helper"]
for idx, (lhs, rhs) in enumerate(zip(patched, target)):
    if lhs != rhs:
        lines.append(f"{payload_len} {idx} {rhs}")
out_lookup.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")
PY
}

IFS=',' read -r -a target_widths <<<"$TARGET_WIDTHS_CSV"

for spec in "${pairs[@]}"; do
  read -r pair channels <<<"$spec"
  pair_root="$OUT_DIR/$pair"
  anchor_src="$SOURCE_ARTIFACT/h${ANCHOR_HEIGHT}_w${ANCHOR_WIDTH}_ic${channels}_oc${channels}_k3"
  anchor_out="$pair_root/anchor"
  mkdir -p "$anchor_out" "$pair_root/targets" "$pair_root/law"
  copy_case_files "$anchor_src" "$anchor_out"
  cp "$anchor_src/extract/package_000/serialized_executable_000.bin" "$anchor_out/serialized_executable_000.bin"

  analysis_json="$pair_root/law/eo_width_band_analysis.json"
  python3 "$REPO_ROOT/tools/instruction_word_field_analysis.py" \
    --entry "${LOW_WIDTH}:$SOURCE_ARTIFACT/h${ANCHOR_HEIGHT}_w${LOW_WIDTH}_ic${channels}_oc${channels}_k3/extract/package_000/serialized_executable_000.bin" \
    --entry "${MID_WIDTH}:$SOURCE_ARTIFACT/h${ANCHOR_HEIGHT}_w${MID_WIDTH}_ic${channels}_oc${channels}_k3/extract/package_000/serialized_executable_000.bin" \
    --entry "${HIGH_WIDTH}:$SOURCE_ARTIFACT/h${ANCHOR_HEIGHT}_w${HIGH_WIDTH}_ic${channels}_oc${channels}_k3/extract/package_000/serialized_executable_000.bin" \
    --chunk-index 0 \
    --tile-size "$TILE_SIZE" \
    --stride auto \
    --top 32 \
    --json-out "$analysis_json" >/dev/null

  for width in "${target_widths[@]}"; do
    if [[ "$width" == "$ANCHOR_WIDTH" ]]; then
      continue
    fi
    src_dir="$SOURCE_ARTIFACT/h${ANCHOR_HEIGHT}_w${width}_ic${channels}_oc${channels}_k3"
    target_out="$pair_root/targets/h${ANCHOR_HEIGHT}_w${width}"
    mkdir -p "$target_out"
    copy_case_files "$src_dir" "$target_out"
    cp "$src_dir/extract/package_000/serialized_executable_000.bin" "$target_out/serialized_executable_000.bin"
    cargo run --quiet --bin word_field_spec_v2 -- \
      --analysis-json "$analysis_json" \
      --base-exec "$anchor_out/serialized_executable_000.bin" \
      --target-exec "$target_out/serialized_executable_000.bin" \
      --low-dim "$LOW_WIDTH" \
      --high-dim "$HIGH_WIDTH" \
      --mid-dim "$MID_WIDTH" \
      --mid-exec "$anchor_out/serialized_executable_000.bin" \
      --target-dim "$width" \
      --tile-size "$TILE_SIZE" \
      --predict-mode threepoint \
      --out-spec "$target_out/field_spec.json" \
      --out-report "$target_out/field_spec.report.json" \
      --out-patchspec "$target_out/field_spec.patchspec" >/dev/null
    lookup_from_predicted "$EO_PAYLOAD_LEN" \
      "$anchor_out/serialized_executable_000.bin" \
      "$target_out/serialized_executable_000.bin" \
      "$target_out/field_spec.patchspec" \
      "$target_out/lookup.patchspec"
  done
done

python3 - <<'PY' "$OUT_DIR" "$OUT_DIR_REL" "$SOURCE_ARTIFACT_REL" "$FAMILY_ID" "$ANCHOR_HEIGHT" "$ANCHOR_WIDTH" "$LOW_WIDTH" "$MID_WIDTH" "$HIGH_WIDTH" "$TILE_SIZE" "$TARGET_WIDTHS_CSV" "$EO_PAYLOAD_LEN" "$LOOKUP_CAP" "$PREDICT_MODE"
import json, pathlib, sys

out_dir = pathlib.Path(sys.argv[1])
out_dir_rel = sys.argv[2]
source_artifact_rel = sys.argv[3]
family_id = sys.argv[4]
anchor_height = int(sys.argv[5])
anchor_width = int(sys.argv[6])
low_width = int(sys.argv[7])
mid_width = int(sys.argv[8])
high_width = int(sys.argv[9])
tile_size = int(sys.argv[10])
target_widths = [int(x) for x in sys.argv[11].split(",") if x]
eo_payload_len = int(sys.argv[12])
lookup_cap = int(sys.argv[13])
predict_mode = sys.argv[14]

regimes = [("p32", 32), ("p64", 64), ("p128", 128)]

def rel(path: pathlib.Path) -> str:
    return str(path.relative_to(out_dir))

def find_single(base: pathlib.Path, pattern: str) -> pathlib.Path:
    matches = list(base.glob(pattern))
    if len(matches) != 1:
        raise SystemExit(f"expected exactly one match for {pattern} under {base}, got {matches}")
    return matches[0]

def find_quant_model(base: pathlib.Path) -> pathlib.Path:
    matches = [p for p in base.glob("*.tflite") if not p.name.endswith("_edgetpu.tflite")]
    if len(matches) != 1:
        raise SystemExit(f"expected exactly one uncompiled model under {base}, got {matches}")
    return matches[0]

def read_patch(path: pathlib.Path):
    rules = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        clean = raw.split("#", 1)[0].replace(",", " ").strip()
        if not clean:
            continue
        parts = clean.split()
        if len(parts) != 3:
            continue
        _plen, off, val = [int(x, 0) for x in parts]
        rules.append([off, val])
    return rules

spec = {
    "schema_version": 2,
    "family_id": family_id,
    "family_mode": "fixed_height_band",
    "fixed_height": anchor_height,
    "anchor_height": anchor_height,
    "anchor_width": anchor_width,
    "eo_payload_len": eo_payload_len,
    "kernel_size": 3,
    "stride": 1,
    "padding": "same",
    "bias": False,
    "source_artifact": source_artifact_rel,
    "asset_root": out_dir_rel,
    "regimes": [],
}

summary = [
    f"family_id={spec['family_id']}",
    f"family_mode={spec['family_mode']}",
    f"fixed_height={anchor_height}",
    f"source_artifact={source_artifact_rel}",
    f"lookup_cap={lookup_cap}",
    f"predict_mode={predict_mode}",
]

for name, channels in regimes:
    pair_dir = out_dir / name
    anchor_dir = pair_dir / "anchor"
    anchor_quant = find_quant_model(anchor_dir)
    anchor_compiled = find_single(anchor_dir, "*_edgetpu.tflite")
    anchor_meta = find_single(anchor_dir, "*.metadata.json")
    anchor_exec = anchor_dir / "serialized_executable_000.bin"
    runtime = {
        "analysis_json": rel(pair_dir / "law" / "eo_width_band_analysis.json"),
        "low_dim": low_width,
        "mid_dim": mid_width,
        "high_dim": high_width,
        "predict_mode": predict_mode,
        "tile_size": tile_size,
        "chunk_index": 0,
        "lane_priority": "lane32,lane16",
    }
    regime = {
        "name": name,
        "channels": channels,
        "anchor_compiled_model": rel(anchor_compiled),
        "anchor_uncompiled_model": rel(anchor_quant),
        "anchor_metadata": rel(anchor_meta),
        "anchor_executable": rel(anchor_exec),
        "field_runtime": runtime,
        "targets": [],
    }
    summary.append(f"[{name}] channels={channels}")
    for width in target_widths:
        if width == anchor_width:
            regime["targets"].append({
                "height": anchor_height,
                "width": width,
                "target_model": rel(anchor_quant),
                "target_compiled_model": rel(anchor_compiled),
                "target_metadata": rel(anchor_meta),
                "source_kind": "noop",
                "field_spec_json": None,
                "lookup_rules": [],
            })
            summary.append(f"  h{anchor_height}_w{width}: source=noop")
            continue
        target_dir = pair_dir / "targets" / f"h{anchor_height}_w{width}"
        target_quant = find_quant_model(target_dir)
        target_compiled = find_single(target_dir, "*_edgetpu.tflite")
        target_meta = find_single(target_dir, "*.metadata.json")
        field_spec = target_dir / "field_spec.json"
        lookup_patch = target_dir / "lookup.patchspec"
        lookup_rules = read_patch(lookup_patch)
        regime["targets"].append({
            "height": anchor_height,
            "width": width,
            "target_model": rel(target_quant),
            "target_compiled_model": rel(target_compiled),
            "target_metadata": rel(target_meta),
            "source_kind": "rule_lookup",
            "field_spec_json": rel(field_spec),
            "lookup_rules": lookup_rules,
        })
        summary.append(
            f"  h{anchor_height}_w{width}: source=rule_lookup lookup_rules={len(lookup_rules)}"
        )
    spec["regimes"].append(regime)

(out_dir / "family.json").write_text(json.dumps(spec, indent=2) + "\n", encoding="utf-8")
(out_dir / "SUMMARY.txt").write_text("\n".join(summary) + "\n", encoding="utf-8")
print(out_dir / "family.json")
print(out_dir / "SUMMARY.txt")
PY

python3 - <<'PY' "$OUT_DIR/family.json" "$REPO_ROOT" "$ANCHOR_HEIGHT"
import json, pathlib, subprocess, sys, tempfile

spec_path = pathlib.Path(sys.argv[1])
repo_root = pathlib.Path(sys.argv[2])
anchor_height = int(sys.argv[3])
spec = json.loads(spec_path.read_text())

sys.path.insert(0, str(repo_root / "tools"))
import parse_edgetpu_executable as pe

def read_chunk(path):
    blob = pathlib.Path(path).read_bytes()
    root = pe._parse_root_table(blob, 0, file_identifier=None)
    tables = pe._read_vector_table_field(root, 5)
    return bytearray(pe._read_vector_bytes_field(tables[0], 0))

def emitted_rules(channels, width):
    fd, path = tempfile.mkstemp(suffix=".patchspec")
    pathlib.Path(path).unlink(missing_ok=True)
    subprocess.run(
        [
            "cargo", "run", "--quiet", "--bin", "conv_k3_eo_emit", "--",
            "--family-spec", str(spec_path),
            "--channels", str(channels),
            "--target-height", str(anchor_height),
            "--target-width", str(width),
            "--out-patchspec", path,
        ],
        cwd=repo_root,
        check=True,
        stdout=subprocess.DEVNULL,
    )
    rules = []
    for raw in pathlib.Path(path).read_text().splitlines():
        clean = raw.split("#", 1)[0].strip()
        if not clean:
            continue
        _plen, off, val = [int(x, 0) for x in clean.split()]
        rules.append((off, val))
    pathlib.Path(path).unlink(missing_ok=True)
    return rules

for regime in spec["regimes"]:
    anchor_exec = read_chunk(spec_path.parent / regime["anchor_executable"])
    for target in regime["targets"]:
        if target["source_kind"] == "noop":
            continue
        target_exec = read_chunk(
            spec_path.parent / f"{regime['name']}/targets/h{anchor_height}_w{target['width']}/serialized_executable_000.bin"
        )
        patched = bytearray(anchor_exec)
        for off, val in emitted_rules(regime["channels"], target["width"]):
            patched[off] = val
        extra = []
        for idx, (lhs, rhs) in enumerate(zip(patched, target_exec)):
            if lhs != rhs:
                extra.append([idx, rhs])
        if extra:
            merged = {off: val for off, val in target.get("lookup_rules", [])}
            for off, val in extra:
                merged[off] = val
            target["lookup_rules"] = [[off, merged[off]] for off in sorted(merged)]

spec_path.write_text(json.dumps(spec, indent=2) + "\n", encoding="utf-8")
PY

python3 - <<'PY' "$OUT_DIR/family.json" "$OUT_DIR/SUMMARY.txt" "$LOOKUP_CAP"
import json, pathlib, sys
spec = json.loads(pathlib.Path(sys.argv[1]).read_text())
lookup_cap = int(sys.argv[3])
lines = [
    f"family_id={spec['family_id']}",
    f"family_mode={spec['family_mode']}",
    f"fixed_height={spec['fixed_height']}",
    f"source_artifact={spec['source_artifact']}",
    f"lookup_cap={lookup_cap}",
    f"predict_mode={spec['regimes'][0]['field_runtime'].get('predict_mode', 'threepoint')}",
]
violations = []
for regime in spec["regimes"]:
    max_lookup = 0
    lines.append(f"[{regime['name']}] channels={regime['channels']}")
    for target in regime["targets"]:
        lookup_rules = len(target.get("lookup_rules", []))
        max_lookup = max(max_lookup, lookup_rules)
        lines.append(
            f"  h{target['height']}_w{target['width']}: source={target['source_kind']} lookup_rules={lookup_rules}"
        )
        if target["source_kind"] != "noop" and lookup_rules > lookup_cap:
            violations.append(
                f"{regime['name']} h{target['height']}_w{target['width']} lookup_rules={lookup_rules} cap={lookup_cap}"
            )
    lines.append(f"  max_lookup_rules={max_lookup}")
pathlib.Path(sys.argv[2]).write_text("\n".join(lines) + "\n", encoding="utf-8")
if violations:
    raise SystemExit("lookup cap exceeded:\n" + "\n".join(violations))
PY

echo "phase5 family assets frozen under: $OUT_DIR"
